### ISSUE TITLE
CreateSmallSphereTest.APR_INPUT_OUTPUT hangs when compiled with Intel compiler

### ISSUE THREAD

**Issue by krzysg** [cheesema/LibAPR#60]
Compiled with Intel's Parallel Studio 2018u1:
```
CC="icc" CXX="icc" CXXFLAGS="-O3 -g" cmake -DAPR_TESTS=1 ..
make -j 7 testAPR
```

Test run with command:
```./test/testAPR  --gtest_filter=*APR_INPUT_OUTPUT*```

Output:
```
[ RUN      ] CreateSmallSphereTest.APR_INPUT_OUTPUT
Opening file: [/projects/ppm/gonciarz/AdaptiveParticleRepresentation/test/files/Apr/sphere_120/sphere_level.tif]
getMesh: MeshData: size(Y/X/Z)=120/120/120 vSize:1728000 vCapacity:1728000 elementSize:2
getMesh: ScanlineSize=240 StripSize=8160 NumberOfStrips=4
Opening file: [/projects/ppm/gonciarz/AdaptiveParticleRepresentation/test/files/Apr/sphere_120/sphere_type.tif]
getMesh: MeshData: size(Y/X/Z)=120/120/120 vSize:1728000 vCapacity:1728000 elementSize:2
getMesh: ScanlineSize=240 StripSize=8160 NumberOfStrips=4
Opening file: [/projects/ppm/gonciarz/AdaptiveParticleRepresentation/test/files/Apr/sphere_120/sphere_original.tif]
getMesh: MeshData: size(Y/X/Z)=120/120/120 vSize:1728000 vCapacity:1728000 elementSize:2
getMesh: ScanlineSize=240 StripSize=8160 NumberOfStrips=4
Opening file: [/projects/ppm/gonciarz/AdaptiveParticleRepresentation/test/files/Apr/sphere_120/sphere_pc.tif]
getMesh: MeshData: size(Y/X/Z)=120/120/120 vSize:1728000 vCapacity:1728000 elementSize:2
getMesh: ScanlineSize=240 StripSize=8160 NumberOfStrips=4
Opening file: [/projects/ppm/gonciarz/AdaptiveParticleRepresentation/test/files/Apr/sphere_120/sphere_x.tif]
getMesh: MeshData: size(Y/X/Z)=120/120/120 vSize:1728000 vCapacity:1728000 elementSize:2
getMesh: ScanlineSize=240 StripSize=8160 NumberOfStrips=4
Opening file: [/projects/ppm/gonciarz/AdaptiveParticleRepresentation/test/files/Apr/sphere_120/sphere_y.tif]
getMesh: MeshData: size(Y/X/Z)=120/120/120 vSize:1728000 vCapacity:1728000 elementSize:2
getMesh: ScanlineSize=240 StripSize=8160 NumberOfStrips=4
Opening file: [/projects/ppm/gonciarz/AdaptiveParticleRepresentation/test/files/Apr/sphere_120/sphere_z.tif]
getMesh: MeshData: size(Y/X/Z)=120/120/120 vSize:1728000 vCapacity:1728000 elementSize:2
getMesh: ScanlineSize=240 StripSize=8160 NumberOfStrips=4
```

Seems that it hangs just before/during writing HDF5 file (comparing to output from gcc/clang). This is the only test that fails.

**Comment by krzysg** [comment]
Seems that problem is with popen command:
```
#0  0x00007ffff5e78b77 in sched_yield () from /usr/lib64/libc.so.6
#1  0x00007ffff69dc0a4 in _INTERNAL_26_______src_z_Linux_util_cpp_c3d2e46c::__kmp_atfork_prepare () at ../../src/z_Linux_util.cpp:1531
#2  0x00007ffff5e5af82 in fork () from /usr/lib64/libc.so.6
#3  0x00007ffff5e09f9c in _IO_proc_open@@GLIBC_2.2.5 () from /usr/lib64/libc.so.6
#4  0x00007ffff5e0a22c in popen@@GLIBC_2.2.5 () from /usr/lib64/libc.so.6
#5  0x00000000004e6613 in exec_blosc[abi:cxx11](char const*) (cmd=0xb <Address 0xb out of bounds>) at /projects/ppm/gonciarz/AdaptiveParticleRepresentation/src/io/hdf5functions_blosc.cpp:25
```

It maybe connected to specific I/O since it was run on Lustre filesystem. Solution which should be good enough is ... not to do that. Anyway what was the purpose to read hash from git and put it to hdf5 files remains unknown..

**Comment by cheesema** [comment]
Hey, the purpose was so that you can track what commit of the repo was used to generate the particular APR. The current way of doing it is pretty ghetto, however, I have found it very useful. So if possible would like to continue this functionality into the future. B

**Comment by krzysg** [comment]
I'm not sure if this is good approach (but maybe it was good in early development stages). We should put there APR version (as soon as it is implemented ;-) ). Hash is not working anyway when command is run not exactly from within git repository and it is giving nasty error outputs like this from HPC:

```
fatal: Not a git repository (or any parent up to mount point /lustre)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```
or from my Mac:
```
fatal: Not a git repository (or any of the parent directories): .git
```
Of course it will not work for LibAPR users in their own projects since it will end up with messages like above or hash from their own git repos which will tell nothing about LibAPR version that created file.

Anyway I have checked and problems seems to be connected to latest Parallel Studio compiler. On previous one (from 2017) everything works. I'm not sure if there is any alternative to 'popen' to have it running with latest compiler.

**Comment by cheesema** [comment]
True, let us also discuss this tomorrow, maybe we can come up with a different solution that gives the functionality that would be useful into the future.

**Comment by krzysg** [comment]
It is fixed now (+ versioning of APR added). It captures hash of LibAPR while it is being built. Works also if LibAPR is used as a submodule.
For now version is fixed to 1.0.0 since we need to decide how/when it should be changed.

**Comment by krzysg** [comment]
Since we are not using popen anymore, reported problem is also solved (re-tested on HPC  with Intel compiler).

**Comment by krzysg** [comment]
UPDATE:  all information about possible cause of this strange hanging process (maybe for future investigating similar/same problems)

popoen was hanging here:
```
#0  0x00007ffff5e78b77 in sched_yield () from /usr/lib64/libc.so.6
#1  0x00007ffff69dc0a4 in _INTERNAL_26_______src_z_Linux_util_cpp_c3d2e46c::__kmp_atfork_prepare () at ../../src/z_Linux_util.cpp:1531
#2  0x00007ffff5e5af82 in fork () from /usr/lib64/libc.so.6
#3  0x00007ffff5e09f9c in _IO_proc_open@@GLIBC_2.2.5 () from /usr/lib64/libc.so.6
#4  0x00007ffff5e0a22c in popen@@GLIBC_2.2.5 () from /usr/lib64/libc.so.6
#5  0x000000000050aa53 in exec_blosc[abi:cxx11](char const*) (cmd=0xb <Address 0xb out of bounds>) at /projects/ppm/gonciarz/AdaptiveParticleRepresentation/src/io/hdf5functions_blosc.cpp:25
```

It happend only for latest (icc (ICC) 18.0.1 20171018) Intel compiler, previous version of icc works (clang and gcc are also OK). It might be connected to OpenMP. Since when 
```
export OMP_NUM_THREADS=1
```
is set, everything works fine. Anyway 'popen' was called from main thread (without OpenMP threads working).
strace for the probmlem:
```
lstat("read_write_test_apr.h5", {st_mode=S_IFREG|0644, st_size=800, ...}) = 0
pipe2([4, 5], O_CLOEXEC)                = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
...
```
Minimal example to reproduce:
``` C++
#include <cstdio>
#include <iostream>
#include <memory>
#include <stdexcept>
#include <string>
#include <array>

std::string exec(const char* cmd) {
    std::array<char, 128> buffer;
    std::string result;
    std::shared_ptr<FILE> pipe(popen(cmd, "r"), pclose);
    if (!pipe) throw std::runtime_error("popen() failed!");
    while (!feof(pipe.get())) {
        if (fgets(buffer.data(), 128, pipe.get()) != nullptr)
            result += buffer.data();
    }
    return result;
}

int main() {
	#pragma omp parallel for
	for (int i = 0; i < 10; ++i) std::cout << ".";
	std::cout << std::endl;
	std::cout << exec("date") << std::endl;
	return 0;
}
```

compiled with:
```
icc -qopenmp popenProblem.cc -opopenProblem
```
